choose_type: hard_i
train_dir: ./data/hh_data_all.jsonl
eval_dir: ./data/hh_data_all.jsonl
output_dir: ./hh_output_h_i
model_name_or_path: RLHFlow/Llama3-SFT-v2.0-epoch3
ref_model: RLHFlow/Llama3-SFT-v2.0-epoch3
bf16: true
per_device_train_batch_size: 1
per_device_eval_batch_size: 1
gradient_accumulation_steps: 16
label_smoothing: 0.1
report_to: wandb
eval_steps: 888888
num_train_epochs: 1
logging_steps: 2
gradient_checkpointing: true
do_train: true
do_eval: false
loss_type: sigmoid
lr_scheduler_type: cosine
optim: adamw_torch
eval_strategy: steps
max_length: 2048
max_prompt_length: 1024
learning_rate: 5.0e-7